server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*.log

  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_log_stream]
        regex: stdout|stderr
        action: keep
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - source_labels:
          [__meta_docker_container_label_com_docker_swarm_service_name]
        target_label: swarm_service
      - source_labels:
          [__meta_docker_container_label_com_docker_swarm_task_name]
        target_label: swarm_task
      - source_labels: [__meta_docker_container_label_com_docker_swarm_node_id]
        target_label: swarm_node
      - source_labels:
          [__meta_docker_container_label_com_docker_swarm_node_name]
        target_label: swarm_node_name
