global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "appChallenge"
    static_configs:
      - targets: ["appChallenge:3000"] # Cambiar "api_host" por el nombre del servicio en Docker

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"] # O el nombre de cada nodo en Swarm

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]
