name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_KEY }}

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.PINGGY_PORT }} ${{ secrets.PINGY_URL }} >> ~/.ssh/known_hosts

      - name: Deploy to Docker Swarm
        run: |
          # Forzar nombre en lowercase para Docker
          IMAGE=$(echo "ghcr.io/${GITHUB_REPOSITORY_OWNER}/${{ secrets.CHALLENGE_IMAGE }}:1.0.0" | tr '[:upper:]' '[:lower:]')
          
          ssh -p ${{ secrets.PINGGY_PORT }} \
              ${{ secrets.SERVER_USERNAME }}@${{ secrets.PINGY_URL }} bash -s << EOF

            echo "Haciendo pull de la imagen $IMAGE"
            docker pull $IMAGE

            echo "Deploying stack"
            docker stack deploy -c docker-compose-PROD.yml challenge_academia_stack

            echo "Checking services status"
            docker stack services challenge_academia_stack
          EOF

      - name: Notify Discord
        if: always()
        uses: Ilshidur/action-discord@master
        with:
          message: "Deployment ${{ job.status }} - Tag: v1.0.0 - Repo: ${{ github.repository }}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
