name: deploy-DEV
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run docker-compose to PROD
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PINGY_URL }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.PINGGY_PORT }}
          script: |
            cd academia2025-challenge
            if docker service ls --format '{{.Name}}' | grep -q "challenge_academia_stack_appChallenge"; then
              echo "Servicio encontrado, actualizando con rolling update y rollback..."
              docker service update \
                --image ghcr.io/${{ secrets.GH_USERNAME }}/${{ secrets.CHALLENGE_IMAGE }}:1.0.0 \
                --update-parallelism 1 \
                --update-delay 10s \
                --update-failure-action rollback \
                challenge_academia_stack_appChallenge
            else
              echo "Servicio no encontrado, desplegando stack..."
              docker stack deploy -c docker-compose-SWARM.yml challenge_academia_stack -d
            fi

      - name: Notify Discord
        if: always()
        uses: Ilshidur/action-discord@master
        with:
          message: "Deployment ${{ job.status }} - Tag: v1.0.0 - Repo: ${{ github.repository }}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
